### PR TITLE
Add optional NaCl encrypted storage

### PR DESCRIPTION
**Pull request by gleb-chipiga**
This code adds cookie storage based on nacl.secret.SecretBox https://pynacl.readthedocs.org/en/latest/secret/

### CODE REVIEW

**Comment by asvetlov** [comment]
Please add nacl key next to https://github.com/aio-libs/aiohttp_session/blob/master/setup.py#L23

**Comment by gleb-chipiga** [comment]
It is already in PR https://github.com/aio-libs/aiohttp_session/pull/20/files#diff-2eeaed663bd0d25b7e608891384b7298R24

**Comment by asvetlov** [comment]
Oops. Sorry.

**Comment by asvetlov** [comment]
Thanks! Merged.

**Pull request merged**
