### PR TITLE
Respect session.max_age in redis storage

### PR DESCRIPTION
**Pull request by artyomboyko**
#44

### CODE REVIEW

**Comment by artyomboyko** [comment]
Didn't find a better way to set expire date in the redis ...

**Comment by artyomboyko** [comment]
@asvetlov  Not sure how to fix it, looks like session.max_age is always empty. Not sure where it's supposed to be set.

**Comment by asvetlov** [comment]
Yes, it is.
The main idea is: use `storage.max_age` as default value for `session.max_age` but allow to user overriding the last value in web-handler on per-user basis.

**Comment by artyomboyko** [comment]
@asvetlov what do you think ? looks like it's done. did I understood you correctly ?

**Comment by asvetlov** [comment]
Cool!

**Pull request merged**
